services:
  ollama:
    image: ollama/ollama:0.11.11
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ./ollama:/root/.ollama

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - HOST=0.0.0.0
      - OLLAMA_HOST=http://ollama:11434
